/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FaqIndexImport } from './routes/faq/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as rootIndexImport } from './routes/(root)/index'
import { Route as TrackTrackIdImport } from './routes/track/$trackId'

// Create/Update Routes

const FaqIndexRoute = FaqIndexImport.update({
  path: '/faq/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const rootIndexRoute = rootIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TrackTrackIdRoute = TrackTrackIdImport.update({
  path: '/track/$trackId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdImport
      parentRoute: typeof rootRoute
    }
    '/(root)/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/faq/': {
      id: '/faq/'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  TrackTrackIdRoute,
  rootIndexRoute,
  AboutIndexRoute,
  FaqIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/track/$trackId",
        "/",
        "/about/",
        "/faq/"
      ]
    },
    "/track/$trackId": {
      "filePath": "track/$trackId.tsx"
    },
    "/": {
      "filePath": "(root)/index.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/faq/": {
      "filePath": "faq/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
